### PR TITLE
Clean up the design.

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by gregdavill** [comment]
This all looks okay. 

Is a single A3 page nicer than two A4 pages for the schematic? I know that's been the preference for other icebreaker boards.
The tricky thing with multipage is the use of pass-through signals or global nets to link signals between the pages.

As mentioned on discord I have PCBs ordered, and they're on their way. So likely this design will see some additional changes based on bringup of that board.

**Comment by esden** [comment]
I would recommend keeping everything on one page as long as possible. Increasing the sheet size to A3 is a reasonable compromise in my opinion.

**Comment by ahmedcharles** [comment]
I mostly just like being able to look at a single page pdf, given that I've never printed a schematic out.

**Comment by gregdavill** [comment]
I do agree the layout is cleaner now. Thanks!

**Pull request merged**
